/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_air_mobilebrowser_opusogg_OggWriter */

#ifndef _Included_com_air_mobilebrowser_opusogg_OggWriter
#define _Included_com_air_mobilebrowser_opusogg_OggWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_air_mobilebrowser_opusogg_OggWriter
 * Method:    native_initOggWriter
 * Signature: (Ljava/lang/String;IIIDILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_air_mobilebrowser_opusogg_OggWriter_native_1initOggWriter
  (JNIEnv *, jobject, jstring, jint, jint, jint, jdouble, jint, jstring);

/*
 * Class:     com_air_mobilebrowser_opusogg_OggWriter
 * Method:    native_writePacket
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_com_air_mobilebrowser_opusogg_OggWriter_native_1writePacket
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_air_mobilebrowser_opusogg_OggWriter
 * Method:    native_closeAndFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_air_mobilebrowser_opusogg_OggWriter_native_1closeAndFree
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
