/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_air_mobilebrowser_opusogg_OggWriter_WritePacketRunnable */

#ifndef _Included_com_air_mobilebrowser_opusogg_OggWriter_WritePacketRunnable
#define _Included_com_air_mobilebrowser_opusogg_OggWriter_WritePacketRunnable
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
