/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_air_mobilebrowser_opusogg_OpusDecoder */

#ifndef _Included_com_air_mobilebrowser_opusogg_OpusDecoder
#define _Included_com_air_mobilebrowser_opusogg_OpusDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_air_mobilebrowser_opusogg_OpusDecoder
 * Method:    native_OpusDecoderCreate
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_air_mobilebrowser_opusogg_OpusDecoder_native_1OpusDecoderCreate
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_air_mobilebrowser_opusogg_OpusDecoder
 * Method:    native_OpusDecoderDecode
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_air_mobilebrowser_opusogg_OpusDecoder_native_1OpusDecoderDecode
  (JNIEnv *, jobject, jobject, jint, jobject);

/*
 * Class:     com_air_mobilebrowser_opusogg_OpusDecoder
 * Method:    native_OpusDecoderRelease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_air_mobilebrowser_opusogg_OpusDecoder_native_1OpusDecoderRelease
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
