/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_air_mobilebrowser_opusogg_OggReader */

#ifndef _Included_com_air_mobilebrowser_opusogg_OggReader
#define _Included_com_air_mobilebrowser_opusogg_OggReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_air_mobilebrowser_opusogg_OggReader
 * Method:    native_initOggReader
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_air_mobilebrowser_opusogg_OggReader_native_1initOggReader
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_air_mobilebrowser_opusogg_OggReader
 * Method:    native_readOpusPackets
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_air_mobilebrowser_opusogg_OggReader_native_1readOpusPackets
  (JNIEnv *, jobject);

/*
 * Class:     com_air_mobilebrowser_opusogg_OggReader
 * Method:    native_closeAndFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_air_mobilebrowser_opusogg_OggReader_native_1closeAndFree
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
