/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_air_mobilebrowser_opusogg_SampleRateChanger */

#ifndef _Included_com_air_mobilebrowser_opusogg_SampleRateChanger
#define _Included_com_air_mobilebrowser_opusogg_SampleRateChanger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_air_mobilebrowser_opusogg_SampleRateChanger
 * Method:    native_initSampleRateChanger
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_air_mobilebrowser_opusogg_SampleRateChanger_native_1initSampleRateChanger
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_air_mobilebrowser_opusogg_SampleRateChanger
 * Method:    native_processSRC
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;IDI)I
 */
JNIEXPORT jint JNICALL Java_com_air_mobilebrowser_opusogg_SampleRateChanger_native_1processSRC
  (JNIEnv *, jobject, jobject, jint, jobject, jint, jdouble, jint);

/*
 * Class:     com_air_mobilebrowser_opusogg_SampleRateChanger
 * Method:    native_release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_air_mobilebrowser_opusogg_SampleRateChanger_native_1release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
